layout_spectrum: 0.3062093
typography_spectrum: 0.5676495
color:
  saturation: 0.9458883
  lightness: 0.0598769
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#020403'
    - '#B50404'
    - '#02A216'
    - '#01FFFF'
  rhythmicContrast: 0.6818715
name: WhiteTieSociety
